---
# tasks file for apt
- name: Install base packages common to all system
  apt: name={{item}} state=present
  with_items:
      - python-apt
      - python-dev
      - build-essential
      - libssl-dev
      - git
      - python-httplib2
  args:
    update_cache: yes

- name: Install the https transport for apt
  apt: name=apt-transport-https state=present


- name: Tag agent with apt in dataloop
  command: /bin/dataloop-agent -a {{ dataloop_api_key }}  tags add  apt
