---
- name: Check for Logstash (prevent re-download)
  stat: path=/opt/logstash
  register: lscheck

- name: Ensure Logstash is installed
  yum: name={{ elk_ls }} state=present
  when: lscheck.stat.isdir is not defined


- name: Add logstash binary to path
  lineinfile: dest=/etc/profile.d/logstash.sh
              state=present create=yes
              line='export PATH=$PATH:/opt/logstash/bin'
              owner=root group=root mode=0644

- name: Ensure logstash service is running
  service: name=logstash state=running enabled=true
