---
# tasks file for elk
# the elk_ variables are defined in ../defaults/main.yml
# You can override them in inventory if required

- name: Ensure Java is installed
  yum: name={{ elk_java }} state=present

# Ideally we'd take RPMs from local repo, but because this is a hacky
# playbook I don't want the yum module to keep downloading only to find
# it doesn't need to install. So, we'll use stat and register to skip
# if already installed.
- name: Check for Elasticsearch (prevent re-download)
  stat: path=/usr/share/elasticsearch/bin
  register: escheck

- name: Ensure Elasticsearch is installed
  yum:  name={{ elk_es }} state=present
  when: escheck.stat.isdir is not defined

# We can choose our 'log aggregator' - default is logstash.
# Override with -e or inventory variable
- include: logstash.yml
  when: elk_logger == 'logstash'

- include: fluentd.yml
  when: elk_logger == 'fluentd'

- name: Fetch Kibana
  get_url: url={{ elk_kibana }} dest=/var/tmp/kibana.tgz

- name: Extract Kibana
  command: /bin/tar xzf /var/tmp/kibana.tgz -C {{ elk_docroot }} creates={{ elk_docroot }}/kibana-{{ elk_kbver }}

- name: Symlink Kibana basedir
  file: src={{ elk_docroot }}/kibana-{{ elk_kbver }} dest={{ elk_docroot }}/kibana
        state=link

- name: Ensure Elasticsearch service is running
  service: name=elasticsearch state=running enabled=true

- name: Tag agent with elk in dataloop
  command: /bin/dataloop-agent -a {{ dataloop_api_key }}  tags add  elk
