---
# tasks file for java
# include the distro-specific stuff
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#
- include: rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Tag agent with java in dataloop
  command: /bin/dataloop-agent -a {{ dataloop_api_key }}  tags add  java
  when: dataloop_enabled == True
