---
# Debian-specific tasks

- name: Install the repo key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: Install the debian repository
  apt_repository: repo="deb http://apt.dockerproject.org/repo {{ansible_distribution|lower}}-{{ansible_distribution_release}} main" state=present

- name: Install Dependencies
  apt: name={{item}} state=present
  with_items:
    - linux-image-virtual
    - linux-image-extra-virtual

- name: Install the AUFS kernel module
  modprobe: name=aufs state=present

- name: We have all the dependencies in place, now install Docker
  apt: name=docker-engine state=present

- name: Update the defaults and restart the service
  template: src=etc_default_docker dest=/etc/default/docker
  notify: restart_docker
