---
# tasks file for nginx
# include the distro-specific stuff
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create the docker group
  group: name=docker state=present

- name: Tag agent with docker in dataloop
  command: /usr/bin/dataloop-agent -a {{ dataloop_api_key }} --add-tags nginx
  when: dataloop_enabled == True
