---
# RHEL Specific tasks

- name: Install nginx
  yum: name=nginx state=present

- name: Copy the default nginx config so we can have monitoring
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0644
  notify: restart nginx
